# Generated by Django 6.0.5 on 2026-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('P', 'Planta'), ('E', 'Electrico'), ('A', 'Agua'), ('T', 'Tierra'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
