# Generated by Django 6.0.5 on 2026-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('P', 'Planta'), ('F', 'Fuego'), ('E', 'Electrico'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
