# Generated by Django 6.0.5 on 2026-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('E', 'Electrico'), ('L', 'Lagartija'), ('T', 'Tierra'), ('P', 'Planta'), ('F', 'Fuego')], max_length=30),
        ),
    ]
